# Is a 4-d boolean function sepereable ?

In [8]:
import numpy as np

## load the data for the function

In [33]:
data = np.genfromtxt('data/input_data_numeric.csv', delimiter=',').T

In [34]:
data.shape

(5, 16)

In [63]:
inputs = data[0]
outputs = data[1:5]

In [69]:
inputs

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [71]:
outputs

array([[-1.,  1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,
         1., -1.,  1.],
       [-1., -1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,
        -1.,  1.,  1.],
       [-1., -1., -1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1., -1.,
         1.,  1.,  1.],
       [-1., -1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1.,
         1.,  1.,  1.]])

## define the perceptron structure

In [103]:
(2*0.2-np.random.random_sample((5,))) - 0.2

array([-0.07978569,  0.09990968,  0.08066047, -0.69804628, -0.39693172])

In [108]:
class Perceptron:
    
    def __init__(self,number_of_input,activation_function,derivate_activation_function,weight=None,bias=None,random_weight=True,weight_range=0.2,bias_range=1):
        
        self.n = number_of_input
        self.activation_function = activation_function
        self.derivate_activation_function = derivate_activation_function
        
        if (weight==None):
            if random_weight:
                self.w = weight_range*(2*np.random.rand(self.n) - 1)
            else:
                self.w = np.zeros(self.n)
        
        else:
            if not(weight.shape== (self.n,)):
                raise ValueError(f"weight param should be of shape ({self.n},) but it is {weight.shape}")
            else:
                self.w = weight
        
        if (bias==None):
            if random_weight:
                self.b= bias_range*(2*np.random.rand()-1)
            else:
                self.b = 0
        
        else:
            self.b = bias
    
    
    def activate(self,x):
        if not(x.shape== (self.n,)):
            raise ValueError(f"input values should be of shape ({self.n},) but it is {x.shape}")
        
        return self.activation_function(self.w@x + self.b)
    
    def derivate(self,x):
        return self.derivate_activation_function(self.w@x + self.b)


In [109]:
activation_func = lambda x : np.tanh(x/2)

In [110]:
derivate_activation_func = lambda x :  (1-np.tanh(x/2)**2)/2

## apply to data

In [111]:
neuron = Perceptron(inputs.shape[0],activation_func,derivate_activation_func)

In [112]:
neuron.activate(outputs[0])

-0.0012060836595460668

In [113]:
neuron.derivate(outputs[0])

0.4999992726811031

In [88]:
def energy_func(p,inputs,real_value):
    return (((p.activate(inputs)-real_value)**2)/2).sum()

def grad_enery(p,inputs,real_value):
    
    grad_w = 2*(p.activate(inputs)-real_value)*inputs*p.derivate(inputs)
    
    grad_b = 2*(p.activate(inputs)-real_value)*p.derivate(inputs)
    
    return grad_w,grad_b

In [89]:
energy_func(neuron,inputs,outputs[0])

16.0

In [90]:
grad_enery(neuron,inputs,outputs[0])

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [92]:
neuron.derivate(inputs)

0.0

In [98]:
derivate_activation_func()

0.0